### ISSUE TITLE
0.8.0 collectstatic does not 'collect' javascript files

### ISSUE THREAD

**Issue by mvillarejo** [bradmontgomery/django-redis-metrics#32]
Hello,

I'm not sure if it is because of my setup but with 0.8.0 version, collectstatic command does not copy the static files from ```redis_metrics``` to my static folder, I have to install development version to make it work, any idea why?

thanks,

**Comment by bradmontgomery** [comment]
I've just tested this on Django 1.7, python 2.7, and it seems to work as expected, so long as you define your `STATIC_ROOT` and you've got `django.contrib.staticfiles` installed.

I'm closing this for now, but if it's still an issue, please re-open.
