### ISSUE TITLE
Backup/restore data to DB

### ISSUE THREAD

**Issue by odedfos** [bradmontgomery/django-redis-metrics#35]
At the moment the metrics are very volatile, as all data is stored only in the Redis server.
It would be useful to be able to dump and load the metric data to the django DB.
Probably not that trivial though...

**Comment by bradmontgomery** [comment]
Hi, I'm closing this as *wontfix* for now. I think [redis persistence](http://redis.io/topics/persistence) is something that most people will need to tweek to fit their needs, so is beyond the scope of this project.
