### ISSUE TITLE
How to import historical/legacy metrics?

### ISSUE THREAD

**Issue by smaccona** [bradmontgomery/django-redis-metrics#43]
I would like to be able to easily import historical metric data which we have stored directly in MySQL, but there doesn't seem to be a way to specify a timestamp for a metric/event. Is there a way to do this?

If not, one way to add this capability would be to add support to `R.metric()` and `R.set_metric()` for an optional `date` argument (with a default of `None`) which in turn would get passed as the `date` argument to `R._build_keys()`. If there is no existing way to import historical data, I can make a pull request for this.

**Comment by bradmontgomery** [comment]
@smaccona Thanks for the PR!  Apologies for not replying to you earlier. I'm going to review this tonight and see about issuing a new release soon.

**Comment by smaccona** [comment]
@bradmontgomery Thanks - no need to look yet, the Travis build is failing (honestly I didn't look at the tests). I'll update the tests and re-issue the PR once I have them passing.
