### ISSUE TITLE
R.get_metric_history() – add to-parameter

### ISSUE THREAD

**Issue by stephanpoetschner** [bradmontgomery/django-redis-metrics#53]
`R.get_metric_history()` handles an options `since` parameter.
When trying to get data from a specific period in the past, an optional `to` parameter would be helpful, to restrict the time-range to a specific interval.

**Comment by stephanpoetschner** [comment]
see my pull request at #54

**Comment by bradmontgomery** [comment]
Closing this since #54 was merged. Thanks again!
